Repository budproj/architecture-decision-log, pull requests merged in 2020-10, with the labels that each got.

#1 Records: Documenting Architecture Decisions
  records/patterns/001-documenting-architecture-decisions.md
Labels: documentation, enhancement

#2 Feature: Github Templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/tech-debt.md
  .github/PULL_REQUEST_TEMPLATE/default.md
Labels: enhancement

#3 Docs: Contributing and Template
  CONTRIBUTING.md
  TEMPLATE.md
Labels: documentation, enhancement

#4 Record: Github Template for Issue and Pull Requests
  records/patterns/002-github-template-for-issues-and-pull-requests.md
  records/patterns/assets/002-github-template-for-issues-and-pull-requests/ISSUE_TEMPLATE/bug-report.md
  records/patterns/assets/002-github-template-for-issues-and-pull-requests/ISSUE_TEMPLATE/feature-request.md
  records/patterns/assets/002-github-template-for-issues-and-pull-requests/ISSUE_TEMPLATE/tech-debt.md
  records/patterns/assets/002-github-template-for-issues-and-pull-requests/PULL_REQUEST_TEMPLATE/default.md
Labels: documentation, enhancement

#5 Record: Domain-Driven Design
  records/patterns/002-github-template-for-issues-and-pull-requests.md
  records/patterns/003-domain-driven-design.md
Labels: documentation, enhancement

#6 Record: Event-Driven Architecture
  .github/PULL_REQUEST_TEMPLATE.md
  records/patterns/004-event-driven-architecture.md
  records/patterns/assets/002-github-template-for-issues-and-pull-requests/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#7 Record: Layered Architecture
  records/patterns/005-layered-architecture.md
  records/patterns/assets/005-layered-architecture/hierarchy-diagram.png
Labels: documentation, enhancement

#8 Record: Test-Driven Development
  records/patterns/006-test-driven-development.md
Labels: documentation, enhancement

#9 Record: Behavior-Driven Development
  records/patterns/007-behavior-driven-development.md
Labels: documentation, enhancement

#10 Record: Development Workflow
  records/patterns/008-development-workflow.md
Labels: documentation, enhancement

#11 Record: Open-Source
  records/patterns/009-open-source.md
Labels: documentation, enhancement

#12 Record: License
  LICENSE
  README.md
  records/patterns/010-licensing.md
Labels: documentation, enhancement

#13 Record: Domain High-Level Overview
  records/domain/001-high-level-overview.md
  records/domain/assets/001-high-level-overview/domain-architecture.png
  records/patterns/003-domain-driven-design.md
Labels: documentation, enhancement

#14 Record: Stack
  records/patterns/011-stack.md
Labels: documentation, enhancement

#15 Refactor: Event-Driven ADR
  records/patterns/004-event-driven-architecture.md
  records/patterns/004-layered-architecture.md
  records/patterns/005-cqrs+es.md
  records/patterns/assets/004-layered-architecture/hierarchy-diagram.png
  records/patterns/assets/005-cqrs+es/cqrs-layered-architecture.png
  records/patterns/assets/005-layered-architecture/hierarchy-diagram.png
Labels: documentation, enhancement

#16 Refactor: Domain Model
  records/domain/001-model-overview.md
  records/domain/assets/001-high-level-overview/domain-architecture.png
  records/domain/assets/001-model-overview/diagram.png
Labels: documentation, enhancement

#17 Record: Microservices overview
  records/domains/001-model-overview.md
  records/domains/assets/001-model-overview/diagram.png
  records/microservices/001-overview.md
  records/microservices/assets/001-overview/diagram.png
Labels: documentation, enhancement

#18 Docs: Adds linting ADR
  records/patterns/011-stack.md
  records/patterns/012-linting.md
Labels: documentation, enhancement

#19 Business: Reducing Technical Complexity
  records/business/001-reducing-initial-technical-complexity.md
  records/microservices/001-overview.md
  records/microservices/assets/001-overview/diagram.png
  records/patterns/005-cqrs+es.md
  records/patterns/006-test-driven-development.md
  records/patterns/007-behavior-driven-development.md
  records/patterns/011-stack.md
Labels: documentation, enhancement

#20 Fix: Microservices names
  records/microservices/assets/001-overview/diagram.png
Labels: bug

#21 Patterns: New backend stack
  records/patterns/011-stack.md
Labels: documentation, enhancement
